### ISSUE TITLE
[BE] 법안 검색 시 사용할 RDS 토큰 인덱스 권한 문제

### ISSUE THREAD

**Issue by ganjisriver** [LawDigest/Lawbag#109]
## 1. 내용
법안 검색 시 성능을 늘려줄 인덱스 토큰 설정을 못함.

## 2. 의논 사항 및 기타
로컬 MySQL DB에서는 가능한데, RDS에서 실행하면 발생하는 권한문제
<img width="901" alt="KakaoTalk_20240329_191621299" src="https://github.com/LawDigest/Lawbag/assets/109566855/80c7fdfa-e622-4ff4-852a-ed3dd0556771">

예상 해결 방법 
- 접속하는 유저에 마스터와 유사한 권한 부여하면 될 것 같음.

**Comment by GotPrgmer** [comment]
log_bin_trust_function_creators 변수 1로 변경하고 확인해 봤지만, 같은 오류가 발생.
![image](https://github.com/LawDigest/Lawbag/assets/55742497/d36452f5-3b28-43bc-9b5c-3acc2258e203)

**Comment by GotPrgmer** [comment]
오라클 클라우드로 서버를 이전하였기에 이슈 닫음.
