### ISSUE TITLE
[BE] 지역구 후보자 지역별 조회

### ISSUE THREAD

**Issue by ganjisriver** [LawDigest/Lawbag#125]
## 1. 내용
![image](https://github.com/LawDigest/Lawbag/assets/109566855/8bbb81ea-4d7c-4d0c-865b-0740ce778f38)

지역구 후보자 조회 
## 2. 의논 사항 및 기타
지역구 후보자들의 공약이 데이터로 제공하고 있지 않아서 추후 순위로 미룸

**Comment by GotPrgmer** [comment]
메인 피드로는 현재 기능을 제공안하고 후보자 별로 공약 pdf링크 스타일로 수정

**Comment by GotPrgmer** [comment]
선거 기간이 지남에 따라 기능 우선순위 하락으로 인해 이슈 잠정적으로 close
