### ISSUE TITLE
[BE] 특정 정당의 발의안을 불러올 때, 속도 개선

### ISSUE THREAD

**Issue by ganjisriver** [LawDigest/Lawbag#177]
## 1. 내용
특정 정당이 발의한 발의안을 가져올 때, 속도가 너무 느림.
## 2. 의논 사항 및 기타
JOIN이 많이 들어가고 대상이 되는 테이블 자체가 전체 데이터의 50% 가까이 되기 때문에, 사실상 인덱스의 적용이 안되는 것 같기도 하다.
1. 속도 개선이 가능한지
2. 이러한 기능이 의미가 있는지
3. 기능 자체를 바꿔야한다면 어떤식으로 바꿔야할지를 고민해야할 것이다.

**Comment by GotPrgmer** [comment]
해당 건은 대표발의자의 관계를 수정하면서
적절한 fetch join과 batch size를 통해 메모리를 고려한 수정으로 개선하였음(10초 이상 -> 약 1초)
