### ISSUE TITLE
[BE] 테스트 코드 작성

### ISSUE THREAD

**Issue by ganjisriver** [LawDigest/Lawbag#181]
## 1. 내용
단위 테스트 테스트 코드 작성
일단 이슈화한 부분이고, 도메인별로 테스트코드 작성할 때마다 이슈 분할해서 가져가는 형식으로 가면 좋을 듯.

**Comment by GotPrgmer** [comment]
추가적으로 서비스 별, 레포지토리 등 부분별 리팩토링시에 필요한 테스트코드를 작성하고 함께 pr 올리는 것으로 함.
