### ISSUE TITLE
[BE]법안별 원문 확인하기 링크 DB에 넣고 api에 반영하기

### ISSUE THREAD

**Issue by GotPrgmer** [LawDigest/Lawbag#195]
## 1. 내용
1. 법안 원문 확인하기 링크 DB에 넣기
2.  법안 상세보기 페이지에서 원문 확인하기로 링크 반영
![image](https://github.com/LawDigest/Lawbag/assets/55742497/948e2b21-6277-4dc4-9c63-4c65e4011be6)

**Comment by ganjisriver** [comment]
아직 완성 안됐는데.. 왜 닫으신거죠 ㅋㅋ;
