### ISSUE TITLE
[BE] 메모리 이슈 발생 및 로그 정리 해결방안

### ISSUE THREAD

**Issue by ganjisriver** [LawDigest/Lawbag#259]
## 1. 내용
배포 환경에서 OutOfMemory 에러가 발생. 쿼리 로그가 많은 영향을 끼치는 것으로 예상되어 로그 출력 관리를 어떻게 할 지 고민할 필요가 있음.

**Comment by GotPrgmer** [comment]
로그의 내용을 간소화하고 엔티티가 수정되거나 삽입되고 조회되는 쿼리들을 한번씩 점검할 필요가 있음
특히 in쿼리에서 (?????????????????????)와 같은 식으로 길게 나오는 부분들을 분석하고 제외할 로그들을 점검해야함

**Comment by GotPrgmer** [comment]
logback을 많이 활용한다고 함
또한 로그들을 주기적으로 저장하고 리프레시하는 방향이 어떨까 함.

**Comment by GotPrgmer** [comment]
로깅 단계 INFO로 변경 Spring actuator를 통해 로깅 레벨 변경하는 것이 좋을 듯.

**Comment by GotPrgmer** [comment]
actuator 사용시, ADMIN계정을 개발팀원에게 부여
role을 ADMIN으로 바꾸고 ADMIN으로만 health나 level 컨트롤이 가능하도록 변경

**Comment by GotPrgmer** [comment]
> actuator 사용시, ADMIN계정을 개발팀원에게 부여 role을 ADMIN으로 바꾸고 ADMIN으로만 health나 level 컨트롤이 가능하도록 변경

그러나 데이터 자동화 작업 다 끝나고 하기
