### ISSUE TITLE
[BE] 정당이 발의한 법안 API 속도 개선

### ISSUE THREAD

**Issue by ganjisriver** [LawDigest/Lawbag#268]
## 1. 내용
정당이 발의한 법안 API 속도가 3~4초 이상 걸리는 현상

**Comment by GotPrgmer** [comment]
날짜와 법안id를 복합인덱스 처리할 예정

firstResult/maxResults specified with collection fetch; applying in memory 로그에 근거하여 이슈 처리

**Comment by ganjisriver** [comment]
복합인덱스를 통해 4초 이상 걸리던 api콜 속도가 0.1초로 단축됨
