### ISSUE TITLE
jpa 메서드로 안가져와지는 오류 원인 파악 - DB관련 이슈 예상

### ISSUE THREAD

**Issue by ganjisriver** [LawDigest/Lawbag#50]
## 1. 내용
JPQL을 활용하지 않고 메서드로만 DB 조회가 안되는 버그 원인 파악

## 2. 의논 사항 및 기타

- [ ] 원인 파악 완료 후 해결 관련 이슈 추가 발급 필요

**Comment by GotPrgmer** [comment]
JPQL을 활용하지 않고 메서드로만 DB 조회가 안되는 버그 원인 파악

여러개의 엔티티에 해당하는 쿼리를 (JPQL를 사용하지 않은)쿼리메소드를 통해 각각 사용하는 부분에서 생기는 버그
아래 버그가 생길 경우를 서술함.

원인 : DTO Projection 에러
    프로젝션에는 Closed projection과 Class-based projection이 있는데
    DTO Projection이 Class-based projection으로 사용됨
    그런데 이때 주의해야할 점이 생성자의 변수와 필드명이 일치해야했는데 이때 일치하지 않아서 생겼던 버그라고 생각함

해당 버그를 고치고 쿼리메소드로 변경하는 것과 JPQL을 사용?

결론은 현재 방식을 유지하는게 바람직하다고 봄
이유는 아래와 같음
1. 성능(JPQL)

엔티티 별로 쿼리메소드를 통해 따로 쿼리를 날렸을 때 성능은 좋지 않을 것이 명백하고
현재의 JPQL을 사용한 방식이 성능면으로 우수

2. 가독성(동점)

또한 하나의 쿼리메소드가 짧지만 여러개의 쿼리메소드가 하나의 기능을 담당하므로 이또한 가독성이 좋지 않음.
현재 JPQL 가독성은 추출하는 필드명이 많아지면 이또한 가독성이 좋지 않음(하지만 쿼리메소드 보다는 좋다고 생각)

3. 유지 보수성(JPQL)

여러개의 가독성이 좋지않은 쿼리메소드를 고치는 것과
그보단 가독성이 좋은 JPQL 쿼리를 고치는 것중에 후자가 낫다고 생각

따라서 현 상태(JPQL)을 유지하도록 함
