### ISSUE TITLE
[BE] 에러 커스텀 및 계층화 작업

### ISSUE THREAD

**Issue by ganjisriver** [LawDigest/Lawbag#79]
## 1. 내용
현재 api 호출 과정에서 에러 발생 시 대부분 단순한 Internal Error로 처리하는데, 에러들을 계층화하고, 상황에 맞는 에러 Response를 반환하는 작업으로 리팩토링

## 2. 의논 사항 및 기타
현재 ResponseEntity 대신 BaseResponse라는 형태로 반환하고 있는데, 추후 헤더나 기타 컨트롤 할 수 있으려면 ResponseEntity를 상속하거나 ResponseEntity를 반환하는 형태로 반환 해야 바람직해 보임.

**Comment by GotPrgmer** [comment]
필터에러들 또한 컨트롤러 에러들과 통합하는 방향도 괜찮다고 봄.
